-- generated by mta/tools/gen_selftest.lua (Lua 5.1/LuaJIT): the state hash of shared/selftest.lua PLAN under LuaJIT and Lua 5.4. Do not edit.
return { seed = 4242, profile = "escalating", days = 2, hash = "449ba8f9380b6128" }
