-- mta/tools/gen_selftest.lua : computes the self-test hash (shared/selftest.lua) with the interpreter that runs this script and writes / checks shared/selftest_data.lua.
--   luajit mta/tools/gen_selftest.lua            print the hash
--   luajit mta/tools/gen_selftest.lua --write    rewrite mta/outbreak/shared/selftest_data.lua
--   lua5.4 mta/tools/gen_selftest.lua --check    exit 1 unless the recorded hash equals this runtime's
local here = (arg and arg[0] or "gen_selftest.lua"):gsub("\\", "/"):match("^(.*)/[^/]*$") or "."
local res = here .. "/../outbreak"
package.path = res .. "/?.lua;" .. package.path
local S = require("shared.selftest")
local r = S.run()
if r.error then io.stderr:write("selftest run failed: " .. r.error .. "\n"); os.exit(2) end
local mode = arg and arg[1]
if mode == "--write" then
	local f = assert(io.open(res .. "/shared/selftest_data.lua", "wb"))
	f:write(string.format('-- generated by mta/tools/gen_selftest.lua (%s): the state hash of shared/selftest.lua PLAN under LuaJIT and Lua 5.4. Do not edit.\nreturn { seed = %d, profile = "%s", days = %d, hash = "%s" }\n',
		_VERSION .. (jit and "/LuaJIT" or ""), S.PLAN.seed, S.PLAN.profile, S.PLAN.days, r.hash))
	f:close()
	print("wrote selftest_data.lua: " .. r.hash)
elseif mode == "--check" then
	package.loaded["shared.selftest_data"] = nil
	local d = require("shared.selftest_data")
	if d.hash == r.hash and r.reload_ok then print("selftest hash OK " .. r.hash .. " (" .. _VERSION .. (jit and "/LuaJIT" or "") .. ", " .. r.ms .. " ms, save " .. r.bytes .. " bytes)")
	else print("selftest hash MISMATCH: recorded " .. tostring(d.hash) .. " computed " .. r.hash .. " reload_ok=" .. tostring(r.reload_ok)); os.exit(1) end
else
	print(r.hash, r.reload_ok, r.bytes, r.ms .. " ms")
end
