-- mta/tools/gen_meta.lua : writes (or checks) mta/outbreak/meta.xml. MTA's meta.xml has no wildcards, so every file the resource needs is listed explicitly; this script lists them
-- from the folders, so a new module cannot be forgotten. Which side gets what:
--   * the CLIENT downloads: the shared helper modules it requires (CLIENT_SHARED below), client/*.lua and the whole ui/ folder (<file>, read with fileOpen by bootstrap_mta.lua / loaded by the browser)
--   * server-only files (server/*.lua, sim/, data/, the host core, view models, survival body, self-test) are marked download="false": the server reads them with fileOpen, no client ever receives them
-- The <settings> block is generated from the defaults in shared/mta_config.lua, so the two cannot drift.
--   luajit mta/tools/gen_meta.lua            rewrite meta.xml
--   luajit mta/tools/gen_meta.lua --check    exit 1 unless meta.xml is exactly what would be written
local here = (arg and arg[0] or "gen_meta.lua"):gsub("\\", "/"):match("^(.*)/[^/]*$") or "."
local res = here .. "/../outbreak"
package.path = res .. "/?.lua;" .. package.path
local Config = require("shared.mta_config")

local CLIENT_SHARED = { util = true, protocol = true, mta_config = true, mta_net = true, json = true, json_decode = true, raymath = true, placement = true }

local function list(dir, pattern)
	local out = {}
	local p = io.popen('cd "' .. res .. '" && find ' .. dir .. ' -type f ' .. (pattern or "") .. ' | LC_ALL=C sort')
	for f in p:lines() do out[#out + 1] = f end
	p:close()
	return out
end

local lines = {}
local function add(s) lines[#lines + 1] = s end

add('<!-- GENERATED by mta/tools/gen_meta.lua: edit the generator or shared/mta_config.lua, not this file. -->')
add('<meta>')
add('\t<info author="Outbreak (private build)" name="Outbreak" version="' .. Config.VERSION .. '" type="gamemode" description="Zombie survival + colony manager on a pure-Lua sim (private, non-commercial)"/>')
add('\t<min_mta_version client="1.5.8" server="1.5.8"/>')
add('\t<oop>false</oop>')
add('')
add('\t<!-- settings: defaults come from shared/mta_config.lua; override them here (restart the resource) -->')
add('\t<settings>')
local s, p, c = Config.server, Config.peds, Config.client
local function bool(v) return v and "1" or "0" end
local settings = {
	{ "seed", s.seed }, { "profile", s.profile }, { "colonists", s.colonists }, { "timescale", s.time_scale }, { "tick_ms", s.tick_ms }, { "autoload", bool(s.autoload) },
	{ "autosave", s.autosave_s }, { "owner_admin", bool(s.owner_admin) }, { "owner_name", s.owner_name }, { "debug", bool(s.debug) }, { "selftest", bool(s.selftest) },
	{ "spawn_player", bool(s.spawn_player) }, { "store", s.store }, { "max_materialized", s.max_materialized }, { "phone", bool(s.phone) }, { "phone_sessions", s.phone_sessions },
	{ "phone_session_s", s.phone_session_s }, { "max_peds", p.max_peds }, { "pool_guard", p.pool_guard },
	{ "max_objects", p.max_objects }, { "origin", string.format("%.2f,%.2f,%.2f", Config.origin.x, Config.origin.y, Config.origin.z) }, { "ui_mode", c.ui_mode },
}
for _, kv in ipairs(settings) do add(string.format('\t\t<setting name="%s" value="%s"/>', kv[1], tostring(kv[2]))) end
add('\t</settings>')
add('')
add('\t<!-- scripts: bootstrap_mta.lua defines `require` over fileOpen on both sides; each side then loads its modules through it -->')
add('\t<script src="bootstrap_mta.lua" type="shared"/>')
add('\t<script src="server/main.lua" type="server"/>')
add('\t<script src="client/main.lua" type="client"/>')
add('')
add('\t<!-- the phone companion: the page is served by the HTTP server at /<resource>/ (default page; MTA asks for a login and checks the ACL right resource.<resource>.http), the one exported function')
add('\t     is what the page calls (POST /<resource>/call/phoneApi, http="true" makes it reachable that way); see README "Phone" -->')
add('\t<html src="ui/phone.html" default="true" raw="true"/>')
add('\t<export function="phoneApi" type="server" http="true"/>')
add('')
add('\t<!-- files the CLIENT downloads: the modules client/main.lua requires, and the browser page with its css / js / fonts (http://mta/local/ui/mta.html) -->')
for _, f in ipairs(list("shared", "-name '*.lua'")) do
	local name = f:match("^shared/(.+)%.lua$")
	if CLIENT_SHARED[name] then add('\t<file src="' .. f .. '"/>') end
end
for _, f in ipairs(list("client", "-name '*.lua'")) do
	if f ~= "client/main.lua" then add('\t<file src="' .. f .. '"/>') end
end
for _, f in ipairs(list("ui")) do
	if f ~= "ui/phone.html" then add('\t<file src="' .. f .. '"/>') end -- (served as the <html> item above, behind the login)
end
add('')
add('\t<!-- NOT listed on purpose: the server-only files (server/*.lua except main.lua, shared/ modules the client does not require, sim/, data/, save/). The server reads them with fileOpen from the')
add('\t     resource folder (verified on the real 1.6 server: an unlisted file opens fine), and MTA\'s HTTP server hands every LISTED <file>, even a download="false" one, to anyone who can reach the HTTP')
add('\t     port WITHOUT a login. Unlisted, the sim and the server code answer 404 over HTTP (tools/phone_e2e.sh asserts it). -->')
add('</meta>')
local text = table.concat(lines, "\n") .. "\n"

local path = res .. "/meta.xml"
if arg and arg[1] == "--check" then
	local f = io.open(path, "rb")
	local cur = f and f:read("*a") or ""
	if f then f:close() end
	if cur == text then print("meta.xml is up to date"); os.exit(0) end
	print("meta.xml is OUT OF DATE: run luajit mta/tools/gen_meta.lua"); os.exit(1)
end
local f = assert(io.open(path, "wb"))
f:write(text)
f:close()
print("wrote meta.xml (" .. #lines .. " lines)")
